export const DATABASE_ID = process.env.NEXT_PUBLIC_DATABASE_ID!

export const TABLES = {
  CALENDAR_EVENTS: process.env.NEXT_PUBLIC_COLLECTION_EVENTS!,
  CALENDARS: process.env.NEXT_PUBLIC_COLLECTION_CALENDARS!,
  ETIQUETTES: process.env.NEXT_PUBLIC_COLLECTION_ETIQUETTES!,
  SEDES: process.env.NEXT_PUBLIC_COLLECTION_SEDES!,
  FACULTIES: process.env.NEXT_PUBLIC_COLLECTION_FACULTIES!,
  PROGRAMS: process.env.NEXT_PUBLIC_COLLECTION_PROGRAMS!,
  PROFILES: process.env.NEXT_PUBLIC_COLLECTION_PROFILES!,
  SCHEDULES: process.env.NEXT_PUBLIC_COLLECTION_SCHEDULES!,
  SCHEDULE_EVENTS: process.env.NEXT_PUBLIC_COLLECTION_SCHEDULE_EVENTS!,
  SCHEDULE_CATEGORIES: process.env.NEXT_PUBLIC_COLLECTION_SCHEDULES_CATEGORIES!,
} as const
