export const DATABASE_ID = process.env.NEXT_PUBLIC_DATABASE_ID!

export const TABLES = {
  CALENDAR_EVENTS: process.env.NEXT_PUBLIC_COLLECTION_EVENTS!,
  CALENDARS: process.env.NEXT_PUBLIC_COLLECTION_CALENDARS!,
  ETIQUETTES: process.env.NEXT_PUBLIC_COLLECTION_ETIQUETTES!,
  SEDES: process.env.NEXT_PUBLIC_COLLECTION_SEDES!,
  FACULTIES: process.env.NEXT_PUBLIC_COLLECTION_FACULTIES!,
  PROGRAMS: process.env.NEXT_PUBLIC_COLLECTION_PROGRAMS!,
  PROFILES: process.env.NEXT_PUBLIC_COLLECTION_PROFILES!,
  SCHEDULES: process.env.NEXT_PUBLIC_COLLECTION_SCHEDULES!,
  SCHEDULE_EVENTS: process.env.NEXT_PUBLIC_COLLECTION_SCHEDULE_EVENTS!,
  SCHEDULE_CATEGORIES: process.env.NEXT_PUBLIC_COLLECTION_SCHEDULES_CATEGORIES!,
} as const

export const BUCKETS = {
  CALENDAR_EVENTS_IMAGES: process.env.NEXT_PUBLIC_CALENDAR_EVENTS_BUCKET_ID!,
  SCHEDULE_EVENTS_IMAGES: process.env.NEXT_PUBLIC_SCHEDULE_EVENTS_BUCKET_ID!,
} as const

export const APPWRITE = {
  ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
  PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!,
} as const
