import { type Models } from "node-appwrite"

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./types`.

export enum Colors {
  GRAY = "gray",
  BLUE = "blue",
  RED = "red",
  GREEN = "green",
  PURPLE = "purple",
  ORANGE = "orange",
  PINK = "pink",
  TEAL = "teal",
  YELLOW = "yellow",
  LIME = "lime",
}

export enum CalendarViews {
  AGENDA = "agenda",
  MONTH = "month",
  WEEK = "week",
  DAY = "day",
}

export type Sedes = Models.Document & {
  name: string
  slug: string
}

export type Faculties = Models.Document & {
  name: string
  slug: string
  sede_id: Sedes["$id"]
}

export type Events = Models.Document & {
  title: string
  description: string | null
  start: Date
  end: Date
  all_day: boolean
  location: string | null
  sedes: Sedes
  faculties: Faculties
  programs: Programs
  calendar_id: Calendars["$id"]
  etiquette_id: Events["$id"]
}

export type Etiquettes = Models.Document & {
  name: string
  color: Colors
  isActive: boolean
  calendarId: Calendars["$id"]
}

export type Calendars = Models.Document & {
  name: string | null
  team_id: string | null
  defaultView: CalendarViews
  slug: string
}

export type Profiles = Models.Document & {}

export type Programs = Models.Document & {
  name: string
  slug: string
  facultiesId: Faculties["$id"]
}
