import { Outfit } from "next/font/google"

import { AppSidebar } from "@/components/app-sidebar"
import { CalendarProvider } from "@/components/calendar/calendar-context"
import NavSearch from "@/components/nav-top"
import { ThemeProvider } from "@/components/theme-provider"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { Toaster } from "@/components/ui/sonner"

import type { Metadata } from "next"
import "./globals.css"

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CalendarProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <NavSearch />
                {children}
              </SidebarInset>
            </SidebarProvider>
          </CalendarProvider>
          <Toaster position="bottom-right" />
        </ThemeProvider>
      </body>
    </html>
  )
}
